// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN9dM_NxK-lG2xxtwtF1qwCq-KZL3XZpM',
    appId: '1:55443923689:web:610e45021fa5b646f60678',
    messagingSenderId: '55443923689',
    projectId: 'real-time-translation-ap-bc082',
    authDomain: 'real-time-translation-ap-bc082.firebaseapp.com',
    databaseURL: 'https://real-time-translation-ap-bc082-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-translation-ap-bc082.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCarzBeT3MrZY_tznMLNMVI4OdJhgC51sM',
    appId: '1:55443923689:android:413b6e6cc5a1b8e4f60678',
    messagingSenderId: '55443923689',
    projectId: 'real-time-translation-ap-bc082',
    databaseURL: 'https://real-time-translation-ap-bc082-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-translation-ap-bc082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLt3GE9PrRC8szTzZrQzVc2zQoA9F5rAk',
    appId: '1:55443923689:ios:e2ef2a63c583cfb3f60678',
    messagingSenderId: '55443923689',
    projectId: 'real-time-translation-ap-bc082',
    databaseURL: 'https://real-time-translation-ap-bc082-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-translation-ap-bc082.firebasestorage.app',
    iosBundleId: 'com.example.realTimeTranslationApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN9dM_NxK-lG2xxtwtF1qwCq-KZL3XZpM',
    appId: '1:55443923689:web:ada9edfe489dbe60f60678',
    messagingSenderId: '55443923689',
    projectId: 'real-time-translation-ap-bc082',
    authDomain: 'real-time-translation-ap-bc082.firebaseapp.com',
    databaseURL: 'https://real-time-translation-ap-bc082-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-translation-ap-bc082.firebasestorage.app',
  );
}
